USE MASTER 
GO 


CREATE DATABASE LOCALIZADOR;
GO 

USE LOCALIZADOR 
GO

--DROP TABLE TB_AMIGO;
--DROP TABLE TB_ENDERECO;
--DROP TABLE TB_PESSOA;



CREATE TABLE TB_PESSOA (
	 ID_PESSOA INT IDENTITY(1,1) PRIMARY KEY
	,DS_USUARIO VARCHAR(20) NOT NULL
	,DS_NOME VARCHAR(50) NOT NULL
);
go


CREATE UNIQUE INDEX IX_USUARIO
ON TB_PESSOA (DS_USUARIO)
gO

CREATE TABLE TB_ENDERECO(
	  ID_ENDERECO INT IDENTITY(1,1) PRIMARY KEY
	 ,ID_PESSOA INT NOT NULL
	 ,NU_LATITUDE FLOAT NOT NULL
	 ,NU_LONGITUTE FLOAT NOT NULL
	 ,FL_ATUAL BIT NOT NULL
);
go

ALTER TABLE TB_ENDERECO
ADD FOREIGN KEY (ID_PESSOA) REFERENCES TB_PESSOA (ID_PESSOA);
go

CREATE TABLE TB_AMIGO (
  	  ID_PESSOA INT NOT NULL REFERENCES TB_PESSOA (ID_PESSOA)
	 ,ID_PESSOA_AMIGA INT NOT NULL REFERENCES TB_PESSOA (ID_PESSOA)
	 ,primary key(ID_PESSOA, ID_PESSOA_AMIGA)
);
go
 


INSERT INTO TB_PESSOA (DS_USUARIO, DS_NOME) VALUES ('JOÃO','JOÃO DA LIBERDADE');
INSERT INTO TB_PESSOA (DS_USUARIO, DS_NOME) VALUES ('MARIA','MARIA DA CONSOLAÇÃO');
INSERT INTO TB_PESSOA (DS_USUARIO, DS_NOME) VALUES ('JOSÉ','JOSÉ DA PENHA');
INSERT INTO TB_PESSOA (DS_USUARIO, DS_NOME) VALUES ('MARIANA','MARIANA DO CAPÃO');
INSERT INTO TB_PESSOA (DS_USUARIO, DS_NOME) VALUES ('CLAUDIANO','CLAUDIANO DO ALVIN');
INSERT INTO TB_PESSOA (DS_USUARIO, DS_NOME) VALUES ('MATILDE','MATILDE DO MUNDO');
go

INSERT INTO TB_AMIGO (ID_PESSOA , ID_PESSOA_AMIGA ) VALUES (1,2);  
INSERT INTO TB_AMIGO (ID_PESSOA , ID_PESSOA_AMIGA ) VALUES (1,3);  
INSERT INTO TB_AMIGO (ID_PESSOA , ID_PESSOA_AMIGA ) VALUES (1,4);  
INSERT INTO TB_AMIGO (ID_PESSOA , ID_PESSOA_AMIGA ) VALUES (1,5);
INSERT INTO TB_AMIGO (ID_PESSOA , ID_PESSOA_AMIGA ) VALUES (1,6);

INSERT INTO TB_AMIGO (ID_PESSOA , ID_PESSOA_AMIGA ) VALUES (2,1);  
INSERT INTO TB_AMIGO (ID_PESSOA , ID_PESSOA_AMIGA ) VALUES (2,3);  
INSERT INTO TB_AMIGO (ID_PESSOA , ID_PESSOA_AMIGA ) VALUES (2,4);  
INSERT INTO TB_AMIGO (ID_PESSOA , ID_PESSOA_AMIGA ) VALUES (2,5);
INSERT INTO TB_AMIGO (ID_PESSOA , ID_PESSOA_AMIGA ) VALUES (2,6);


INSERT INTO TB_AMIGO (ID_PESSOA , ID_PESSOA_AMIGA ) VALUES (3,1);  
INSERT INTO TB_AMIGO (ID_PESSOA , ID_PESSOA_AMIGA ) VALUES (3,2);  
INSERT INTO TB_AMIGO (ID_PESSOA , ID_PESSOA_AMIGA ) VALUES (3,4);  
INSERT INTO TB_AMIGO (ID_PESSOA , ID_PESSOA_AMIGA ) VALUES (3,5);
INSERT INTO TB_AMIGO (ID_PESSOA , ID_PESSOA_AMIGA ) VALUES (3,6);



INSERT INTO TB_AMIGO (ID_PESSOA , ID_PESSOA_AMIGA ) VALUES (4,1);  
INSERT INTO TB_AMIGO (ID_PESSOA , ID_PESSOA_AMIGA ) VALUES (4,2);  
INSERT INTO TB_AMIGO (ID_PESSOA , ID_PESSOA_AMIGA ) VALUES (4,3);  
INSERT INTO TB_AMIGO (ID_PESSOA , ID_PESSOA_AMIGA ) VALUES (4,5);
INSERT INTO TB_AMIGO (ID_PESSOA , ID_PESSOA_AMIGA ) VALUES (4,6);


INSERT INTO TB_AMIGO (ID_PESSOA , ID_PESSOA_AMIGA ) VALUES (5,1);  
INSERT INTO TB_AMIGO (ID_PESSOA , ID_PESSOA_AMIGA ) VALUES (5,2);  
INSERT INTO TB_AMIGO (ID_PESSOA , ID_PESSOA_AMIGA ) VALUES (5,3);  
INSERT INTO TB_AMIGO (ID_PESSOA , ID_PESSOA_AMIGA ) VALUES (5,4);
INSERT INTO TB_AMIGO (ID_PESSOA , ID_PESSOA_AMIGA ) VALUES (5,6);


INSERT INTO TB_AMIGO (ID_PESSOA , ID_PESSOA_AMIGA ) VALUES (6,1);  
INSERT INTO TB_AMIGO (ID_PESSOA , ID_PESSOA_AMIGA ) VALUES (6,2);  
INSERT INTO TB_AMIGO (ID_PESSOA , ID_PESSOA_AMIGA ) VALUES (6,3);  
INSERT INTO TB_AMIGO (ID_PESSOA , ID_PESSOA_AMIGA ) VALUES (6,4);
INSERT INTO TB_AMIGO (ID_PESSOA , ID_PESSOA_AMIGA ) VALUES (6,5);


INSERT INTO TB_ENDERECO (ID_PESSOA, NU_LATITUDE, NU_LONGITUTE, FL_ATUAL  )
SELECT ID_PESSOA, -23.558287, -46.637079, 1 FROM TB_PESSOA WHERE DS_NOME = 'JOÃO DA LIBERDADE';

INSERT INTO TB_ENDERECO (ID_PESSOA, NU_LATITUDE, NU_LONGITUTE, FL_ATUAL  )
SELECT ID_PESSOA, -23.552608, -46.655605, 1 FROM TB_PESSOA WHERE DS_NOME = 'MARIA DA CONSOLAÇÃO';

INSERT INTO TB_ENDERECO (ID_PESSOA, NU_LATITUDE, NU_LONGITUTE, FL_ATUAL  )
SELECT ID_PESSOA, -23.529604, -46.542690, 1 FROM TB_PESSOA WHERE DS_NOME = 'JOSÉ DA PENHA';

INSERT INTO TB_ENDERECO (ID_PESSOA, NU_LATITUDE, NU_LONGITUTE, FL_ATUAL  )
SELECT ID_PESSOA, -23.670779, -46.764480, 1 FROM TB_PESSOA WHERE DS_NOME = 'MARIANA DO CAPÃO';
go

INSERT INTO TB_ENDERECO (ID_PESSOA, NU_LATITUDE, NU_LONGITUTE, FL_ATUAL  )
SELECT ID_PESSOA, -23.537046, -46.475359, 1 FROM TB_PESSOA WHERE DS_NOME = 'CLAUDIANO DO ALVIN';

INSERT INTO TB_ENDERECO (ID_PESSOA, NU_LATITUDE, NU_LONGITUTE, FL_ATUAL  )
SELECT ID_PESSOA, -23.538047, -46.525543, 1 FROM TB_PESSOA WHERE DS_NOME = 'MATILDE DO MUNDO';
go


IF EXISTS ( SELECT *  FROM   sysobjects 
            WHERE  id = object_id(N'[dbo].[SELECIONAR_ENDERECO]') 
                   and OBJECTPROPERTY(id, N'IsProcedure') = 1 )
BEGIN
    DROP PROCEDURE SELECIONAR_ENDERECO;
END
GO

CREATE PROCEDURE SELECIONAR_ENDERECO 
		@ID_ENDERECO INT

AS

BEGIN 
		SELECT 
			 ID_ENDERECO AS IdEndereco
			,ID_PESSOA AS IdPessoa
			,NU_LONGITUTE AS nuLatitude
			,NU_LATITUDE AS nuLongitude
			,FL_ATUAL AS FlagAtual
		FROM TB_ENDERECO
		WHERE ID_ENDERECO = @ID_ENDERECO
END
GO




IF EXISTS ( SELECT *  FROM   sysobjects 
            WHERE  id = object_id(N'[dbo].[SELECIONAR_LISTA_ENDERECO]') 
                   and OBJECTPROPERTY(id, N'IsProcedure') = 1 )
BEGIN
    DROP PROCEDURE [dbo].[SELECIONAR_LISTA_ENDERECO]
END
GO


CREATE PROCEDURE SELECIONAR_LISTA_ENDERECO 
		@ID_PESSOA INT
AS

BEGIN 
		SELECT 
			 ID_ENDERECO AS IdEndereco
			,ID_PESSOA AS IdPessoa
			,NU_LONGITUTE AS nuLatitude
			,NU_LATITUDE AS nuLongitude
			,FL_ATUAL AS FlagAtual
		FROM TB_ENDERECO
		WHERE ID_PESSOA = @ID_PESSOA
END
GO


  
IF EXISTS ( SELECT *  FROM   sysobjects 
            WHERE  id = object_id(N'[dbo].[SELECIONAR_PESSOA]') 
                   and OBJECTPROPERTY(id, N'IsProcedure') = 1 )
BEGIN
    DROP PROCEDURE [dbo].[SELECIONAR_PESSOA]
END
GO


CREATE PROCEDURE SELECIONAR_PESSOA 
		@ID_PESSOA INT
AS
BEGIN 
		SELECT 
			  ID_PESSOA AS IdPessoa
			 ,DS_USUARIO AS Usuario
			 ,DS_NOME AS Nome
		FROM TB_PESSOA
		WHERE ID_PESSOA = @ID_PESSOA
END
GO


IF EXISTS ( SELECT *  FROM   sysobjects 
            WHERE  id = object_id(N'[dbo].[SELECIONAR_LISTA_AMIGO]') 
                   and OBJECTPROPERTY(id, N'IsProcedure') = 1 )
BEGIN
    DROP PROCEDURE SELECIONAR_LISTA_AMIGO
END
GO


CREATE PROCEDURE SELECIONAR_LISTA_AMIGO 
	              @DS_USUARIO VARCHAR(20)
AS
BEGIN 
		SELECT 
			  B.ID_PESSOA AS IdPessoa
			 ,B.DS_USUARIO AS Usuario
			 ,B.DS_NOME AS Nome
			 ,C.ID_ENDERECO AS IdEndereco
			 ,C.ID_PESSOA AS IdPessoa
			 ,C.NU_LONGITUTE AS nuLongitude
			 ,C.NU_LATITUDE AS nuLatitude
		FROM TB_AMIGO A 
		INNER JOIN TB_PESSOA B
		  ON B.ID_PESSOA = A.ID_PESSOA_AMIGA
		LEFT OUTER JOIN TB_ENDERECO C
		  ON C.ID_PESSOA = A.ID_PESSOA_AMIGA 
		 AND C.FL_ATUAL = 1
		INNER JOIN TB_PESSOA D
		  ON D.ID_PESSOA = A.ID_PESSOA 
		WHERE D.DS_USUARIO = @DS_USUARIO 
END
GO



IF EXISTS ( SELECT *  FROM   sysobjects 
            WHERE  id = object_id(N'[dbo].[SELECIONAR_LISTA_USUARIO]') 
                   and OBJECTPROPERTY(id, N'IsProcedure') = 1 )
BEGIN
    DROP PROCEDURE [dbo].[SELECIONAR_LISTA_USUARIO]
END
GO


CREATE PROCEDURE SELECIONAR_LISTA_USUARIO 
AS
BEGIN 
		SELECT 
			  A.ID_PESSOA AS IdPessoa
			 ,A.DS_USUARIO AS Usuario
			 ,A.DS_NOME AS Nome
		FROM  TB_PESSOA A
END
GO

